music_app/config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  resource :session, only: [:create, :new, :destroy]
  resources :users, only: [:create, :new, :show]
  resources :bands
end

music_app/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

music_app/app/models/band.rb
class Band < ApplicationRecord

    validates :name, uniqueness: true, presence: true

end

music_app/app/models/user.rb
class User < ApplicationRecord

    validates :email, :password_digest, :session_token, presence: true
    validates :password, length: {minimum: 6}, allow_nil: true
    validates :email, :session_token, uniqueness: true
    attr_reader :password
    before_validation :ensure_session_token

    def self.find_by_credentials(email,password)
        user = User.find_by(email: email)
        if user && user.is_password?(password)
            return user
        else
            return nil
        end
    end

    def password=(password)
        @password = password
        self.password_digest = BCrypt::Password.create(password)
    end

    def is_password?(password)
        BCrypt::Password.new(self.password_digest).is_password?(password)
    end

    def reset_session_token
        self.session_token = generate_unique_session_token
        self.save!
        return self.session_token
    end

    def generate_unique_session_token
        token = SecureRandom::urlsafe_base64
        while User.exists?(session_token: token)
            token = SecureRandom::urlsafe_base64
        end
        return token
    end

    def ensure_session_token
        self.session_token ||= generate_unique_session_token
    end
end

music_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    helper_method :logged_in?, :current_user

    def current_user
        @current_user ||= User.find_by(session_token: session[:session_token])
    end

    def require_logged_in
        redirect_to new_session unless logged_in?
    end

    def require_logged_out
        redirect_to users_url if logged_in?
    end

    def logged_in?
        !!current_user
    end

    def login(user)
        session[:session_token] = user.reset_session_token
    end

    def logout
        @current_user.reset_session_token if logged_in?
        session[:session_token] = nil
        @current_user = nil
    end
end

music_app/app/controllers/bands_controller.rb
class BandsController < ApplicationController

    def index
        @bands = Band.all
        render :index
    end

    def create
        @band = Band.new(band_params)
        @band.save!
        redirect_to bands_url
    end

    def new
        @band = Band.new
        render :new
    end

    def edit
        @band = Band.find_by(band_params)
    end

    def show
        render :show
    end

    def update

    end

    def destroy

    end

    private
    def band_params
        params.require(:band).permit(:name)
    end
end

music_app/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def new
        @user = User.new
        render :new
    end

    def create
        @user = User.find_by_credentials(params[:user][:email],params[:user][:password])
        if @user
            login(@user)
            redirect_to bands_url
        else
            render :new
        end
    end

    def destroy
        logout
        render :new
    end
end

music_app/app/controllers/users_controller.rb
class UsersController < ApplicationController
    def create
        @user = User.create(user_params)
        if @user.save!
            login(@user)
            redirect_to bands_url
        else
            render :new
        end
    end

    def new
        render :new
    end

    def show
        @users = User.all
        render :show
    end

    private
    def user_params
        params.require(:user).permit(:email, :password)
    end
end 

music_app/app/helpers/application_helper.rb
module ApplicationHelper
end

music_app/app/helpers/bands_helper.rb
module BandsHelper
end

music_app/app/views/bands/index.html.erb
<h1>Bands<h1>
<a href="<%= new_band_url %>">new band</a>
<ul>
<% @bands.each do |band| %>
    <li><%= band.name %></li>
<% end %>
<ul>

music_app/app/views/bands/new.html.erb
<h1>New Band</h1>
<form action="<%= bands_url %>" method="post">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>"/>
    <input type="text" name="band[name]">
    <button>Submit</button>
</form>

music_app/app/views/bands/show.html.erb
<h1><%= @band.name %></h1>
<a href="<%= edit_band_url %>">edit</a>

music_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MusicApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application" %>
  </head>

  <body>
    <%= yield %>

    <% if logged_in? %>
      <form action="<%= session_url %>" method="POST">
        <input type="hidden" name="_method" value="DELETE">
        <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>"/>
        <input type="submit" value="Log Out">
      </form>
    <% else %>
      <form action="<%= new_session_url %>" method="POST">
        <input type="hidden" name="_method" value="GET">
        <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>"/>
        <input type="submit" value="Log In">
      </form>
    <% end %>
    <a href="<%= new_user_url %>">Sign Up</a>
  </body>
</html>

music_app/app/views/users/new.html.erb
<h1>Sign Up</h1>
<form action="<%= users_url %>" method="POST">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>"/>
    <input type="text" name="user[email]">
    <input type="password" name="user[password]">
    <button>Sign Up</button>
</form>